theme: jekyll-theme-midnight
title: "FRQ Frontend"
description: "Demonstrating Java Backend via Github Pages"
gitorg: "https://github.com/AD1616/FRQ-Frontend"
date: "June 26 to July 1 2023"
google_analytics:
url: https://ad1616.github.io
baseurl: /FRQ-Frontend